name: ml-kirigami

channels:
  - defaults

dependencies:
# Mostly used Python libs
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - -r requirements.txt

# IPython modules
  - ipywidgets
  # - jupyterlab
  # - jupyterlab-git
  # - jupyterlab-nvdashboard
  # - jupyterlab-lsp
  # - python-language-server
  
# Machine learning modules
  - scikit-learn
  # - pytorch=1.9
  # - pytorch-lightning
  # - torchvision