name: ml-kirigami-tf-2.6

channels:
  - defaults
  - conda-forge
dependencies:
# Mostly used Python libs
  - python=3.10.4
  - autopep8=1.6.0
  - black=19.10b0
  - pip=22.1.2
  - numpy=1.22.3
  - scipy=1.7.3
  - pandas=1.4.3
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - pip:
    - tensorflow==2.9.1
# IPython modules
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  # - jupyterlab
  # - jupyterlab-git
  # - jupyterlab-nvdashboard
  # - jupyterlab-lsp
  # - python-language-server
  
# Machine learning modules
  - scikit-learn=1.1.1
  # - pytorch=1.9
  # - pytorch-lightning
  # - torchvision

# GPU 
  - cudatoolkit=11.2 
  - cudnn=8.1.0