name: ml-kirigami-tf-2.6

channels:
  - defaults
  - conda-forge
dependencies:
# Mostly used Python libs
  - python
  - autopep8
  - black
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - tensorflow
# IPython modules
  - ipywidgets
  # - jupyterlab
  # - jupyterlab-git
  # - jupyterlab-nvdashboard
  # - jupyterlab-lsp
  # - python-language-server
  
# Machine learning modules
  - scikit-learn
  # - pytorch=1.9
  # - pytorch-lightning
  # - torchvision

# GPU 
  - cudatoolkit=11.2 
  - cudnn=8.1.0